#!/usr/bin/env bash

#update pip
python3 -m pip install --upgrade pip

#Install some stuff
python3 -m pip install .bin/AVGN/.
python3 -m pip install Cython==0.29.13 
python3 -m pip install Jinja2==2.10.3
python3 -m pip install MarkupSafe==1.1.1
python3 -m pip install Pillow==6.2.1
python3 -m pip install PyWavelets==1.1.1
python3 -m pip install Pygments==2.4.2
python3 -m pip install Send2Trash==1.5.0
python3 -m pip install SoundFile==0.10.2
python3 -m pip install asteval==0.9.16
python3 -m pip install attrs==19.3.0
python3 -m pip install audioread==2.1.8
python3 -m pip install backcall==0.1.0
python3 -m pip install bleach==3.1.0
python3 -m pip install cffi==1.13.1 
python3 -m pip install cycler==0.10.0
python3 -m pip install decorator==4.4.1
python3 -m pip install defusedxml==0.6.0
python3 -m pip install entrypoints==0.3  
python3 -m pip install h5py==2.10.0      
python3 -m pip install hdbscan==0.8.23   
python3 -m pip install imageio==2.6.1    
python3 -m pip install importlib-metadata==0.23
python3 -m pip install ipykernel==5.1.3        
python3 -m pip install ipython-genutils==0.2.0 
python3 -m pip install ipython==7.9.0       
python3 -m pip install ipywidgets==7.5.1    
python3 -m pip install jedi==0.15.1      
python3 -m pip install joblib==0.14.0    
python3 -m pip install jsonschema==3.1.1 
python3 -m pip install jupyter-client==5.3.4
python3 -m pip install jupyter-core==4.6.1   
python3 -m pip install kiwisolver==1.1.0     
python3 -m pip install librosa==0.7.1        
python3 -m pip install llvmlite==0.30.0     
python3 -m pip install lmfit==0.9.14       
python3 -m pip install matplotlib==3.1.1        
python3 -m pip install mistune==0.8.4 
python3 -m pip install more-itertools==7.2.0
python3 -m pip install nbconvert==5.6.1     
python3 -m pip install nbformat==4.4.0      
python3 -m pip install networkx==2.4        
python3 -m pip install notebook==6.0.1      
python3 -m pip install numba==0.46.0     
python3 -m pip install numpy==1.17.3     
python3 -m pip install pandas==0.25.2     
python3 -m pip install pandocfilters==1.4.2        
python3 -m pip install parso==0.5.1        
python3 -m pip install pexpect==4.7.0      
python3 -m pip install pickleshare==0.7.5  
python3 -m pip install prometheus-client==0.7.1   
python3 -m pip install prompt-toolkit==2.0.10     
python3 -m pip install ptyprocess==0.6.0      
python3 -m pip install pycparser==2.19        
python3 -m pip install pyparsing==2.4.2       
python3 -m pip install pyrsistent==0.15.5     
python3 -m pip install python-dateutil==2.8.0 
python3 -m pip install pytz==2019.3       
python3 -m pip install pyzmq==18.1.0       
python3 -m pip install resampy==0.2.2        
python3 -m pip install scikit-image==0.16.2       
python3 -m pip install scikit-learn==0.21.3       
python3 -m pip install scipy==1.3.1        
python3 -m pip install seaborn==0.9.0      
python3 -m pip install six==1.12.0      
python3 -m pip install sklearn==0.0     
python3 -m pip install terminado==0.8.2 
python3 -m pip install testpath==0.4.2  
python3 -m pip install tornado==6.0.3   
python3 -m pip install tqdm==4.36.1     
python3 -m pip install traitlets==4.3.3 
python3 -m pip install umap-learn==0.3.10
python3 -m pip install uncertainties==3.1.2 
python3 -m pip install wcwidth==0.1.7       
python3 -m pip install webencodings==0.5.1  
python3 -m pip install widgetsnbextension==3.5.1
python3 -m pip install zipp==0.6.0
